final_conditions = [[1, 7], [2, 8], [3, 9], [4, 10], [5, 11], [6, 12]]
r0 = [13, 14, 15, 16]
s0 = [1, 2, 3, 4, 5, 6]
sF = [7, 8, 9, 10, 11, 12]
shapes = [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]]

[[operations]]
pre = [[2, 8], [1, 7]]
post = [[3, 3]]
station_id = 3
id = 62
dt = 0
[[operations]]
pre = [[3, 9]]
post = []
station_id = -1
id = 63
dt = 0
[[operations]]
pre = [[5, 11]]
post = [[6, 6]]
station_id = 3
id = 64
dt = 0
[[operations]]
pre = [[4, 10]]
post = [[5, 5]]
station_id = 2
id = 65
dt = 0
[[operations]]
pre = [[6, 12]]
post = []
station_id = -1
id = 66
dt = 0
