name = "TaskGraphs"
uuid = "6635cb54-791c-11e9-2805-8512ad3937f9"
authors = ["kylebrown <kylejbrown17@gmail.com>"]
version = "0.1.0"

[deps]
CRCBS = "edef75b8-3ac4-11e9-0392-bf149c536ee3"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GraphPlottingBFS = "277fd268-772f-11e9-01e2-fbbcabd1ad4a"
GraphUtils = "5d4bc1c0-0fb7-11e9-3252-b1aa07358cab"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOML = "191fdcea-f9f2-43e0-b922-d33f71e2abc3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
