final_conditions = [[1, 557], [2, 482], [3, 208], [4, 234], [5, 506], [6, 62], [7, 362], [8, 405], [9, 125], [10, 68], [11, 196], [12, 494]]
r0 = [444, 158, 352, 286, 408, 534, 560, 316, 459, 443, 201, 547, 192, 128, 597, 19, 409, 428, 568, 54, 194, 479, 530, 50]
s0 = [225, 136, 365, 355, 398, 240, 270, 337, 410, 416, 276, 130]
sF = [557, 482, 208, 234, 506, 62, 362, 405, 125, 68, 196, 494]
shapes = [[1, 2], [2, 1], [1, 1], [1, 1], [1, 2], [2, 1], [2, 1], [1, 2], [2, 1], [1, 1], [1, 1], [1, 2]]
initial_conditions = [[1, 225], [2, 136], [3, 365], [4, 355], [5, 398], [6, 240], [7, 270], [8, 337], [9, 410], [10, 416], [11, 276], [12, 130]]

[[operations]]
pre = [[10, 68], [11, 196]]
post = [[12, 130]]
station_id = 12
id = 2129
dt = 0
[[operations]]
pre = [[7, 362], [8, 405], [9, 125]]
post = [[11, 276]]
station_id = 11
id = 2130
dt = 0
[[operations]]
pre = [[4, 234], [6, 62], [5, 506]]
post = [[7, 270]]
station_id = 7
id = 2131
dt = 0
[[operations]]
pre = [[2, 482], [3, 208], [1, 557]]
post = [[5, 398]]
station_id = 5
id = 2132
dt = 0
[[operations]]
pre = [[12, 494]]
post = []
station_id = -1
id = 2133
dt = 0
