final_conditions = [[1, 411], [2, 82], [3, 366], [4, 251], [5, 527], [6, 226], [7, 202], [8, 417], [9, 111], [10, 208], [11, 514], [12, 131], [13, 387], [14, 247], [15, 348], [16, 539], [17, 234], [18, 494]]
r0 = [165, 587, 181, 305, 314, 201, 190, 141, 553, 457, 216, 260, 455, 110, 291, 459, 297, 37, 303, 512, 152, 516, 325, 96]
s0 = [550, 240, 388, 89, 343, 258, 410, 532, 136, 215, 85, 124, 118, 505, 81, 69, 63, 501]
sF = [411, 82, 366, 251, 527, 226, 202, 417, 111, 208, 514, 131, 387, 247, 348, 539, 234, 494]
shapes = [[1, 2], [2, 1], [1, 1], [2, 1], [1, 1], [1, 1], [1, 2], [1, 2], [1, 1], [2, 1], [2, 1], [2, 1], [2, 1], [1, 2], [1, 2], [1, 1], [1, 2], [1, 1]]
initial_conditions = [[1, 550], [2, 240], [3, 388], [4, 89], [5, 343], [6, 258], [7, 410], [8, 532], [9, 136], [10, 215], [11, 85], [12, 124], [13, 118], [14, 505], [15, 81], [16, 69], [17, 63], [18, 501]]

[[operations]]
pre = [[17, 234]]
post = [[18, 501]]
station_id = 18
id = 2134
dt = 0
[[operations]]
pre = [[16, 539], [14, 247], [15, 348]]
post = [[17, 63]]
station_id = 17
id = 2135
dt = 0
[[operations]]
pre = [[13, 387]]
post = [[15, 81]]
station_id = 15
id = 2136
dt = 0
[[operations]]
pre = [[11, 514], [12, 131]]
post = [[13, 118]]
station_id = 13
id = 2137
dt = 0
[[operations]]
pre = [[9, 111], [8, 417], [10, 208]]
post = [[12, 124]]
station_id = 12
id = 2138
dt = 0
[[operations]]
pre = [[6, 226], [7, 202]]
post = [[9, 136]]
station_id = 9
id = 2139
dt = 0
[[operations]]
pre = [[3, 366], [4, 251], [5, 527]]
post = [[6, 258]]
station_id = 6
id = 2140
dt = 0
[[operations]]
pre = [[2, 82]]
post = [[11, 85]]
station_id = 11
id = 2141
dt = 0
[[operations]]
pre = [[1, 411]]
post = [[7, 410]]
station_id = 7
id = 2142
dt = 0
[[operations]]
pre = [[18, 494]]
post = []
station_id = -1
id = 2143
dt = 0
