final_conditions = [[1, 383], [2, 476], [3, 482], [4, 94], [5, 488], [6, 277], [7, 226], [8, 506], [9, 366], [10, 208], [11, 107], [12, 251]]
r0 = [472, 441, 517, 4, 350, 347, 59, 145, 463, 204, 18, 542, 606, 375, 474, 552, 465, 571, 322, 216, 561, 35, 548, 324]
s0 = [550, 118, 89, 392, 349, 244, 203, 483, 495, 404, 410, 264]
sF = [383, 476, 482, 94, 488, 277, 226, 506, 366, 208, 107, 251]
shapes = [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 550], [2, 118], [3, 89], [4, 392], [5, 349], [6, 244], [7, 203], [8, 483], [9, 495], [10, 404], [11, 410], [12, 264]]

[[operations]]
pre = [[10, 208], [11, 107]]
post = [[12, 264]]
station_id = 12
id = 2102
dt = 0
[[operations]]
pre = [[8, 506], [9, 366]]
post = [[11, 410]]
station_id = 11
id = 2103
dt = 0
[[operations]]
pre = [[5, 488], [6, 277], [7, 226]]
post = [[10, 404]]
station_id = 10
id = 2104
dt = 0
[[operations]]
pre = [[4, 94], [2, 476], [3, 482]]
post = [[7, 203]]
station_id = 7
id = 2105
dt = 0
[[operations]]
pre = [[1, 383]]
post = [[6, 244]]
station_id = 6
id = 2106
dt = 0
[[operations]]
pre = [[12, 251]]
post = []
station_id = -1
id = 2107
dt = 0
