final_conditions = [[1, 68], [2, 265], [3, 482], [4, 137], [5, 510], [6, 74], [7, 90], [8, 348], [9, 62], [10, 259]]
r0 = [444, 158, 352, 286, 408, 534, 560, 316, 459, 443, 201, 547, 192, 128, 597, 19, 409, 428, 568, 54, 194, 479, 530, 50, 275, 232, 540, 345, 88, 587]
s0 = [81, 398, 89, 124, 225, 538, 209, 264, 63, 544]
sF = [68, 265, 482, 137, 510, 74, 90, 348, 62, 259]
shapes = [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 81], [2, 398], [3, 89], [4, 124], [5, 225], [6, 538], [7, 209], [8, 264], [9, 63], [10, 544]]

[[operations]]
pre = [[9, 62]]
post = [[10, 544]]
station_id = 10
id = 50
dt = 0
[[operations]]
pre = [[8, 348]]
post = [[9, 63]]
station_id = 9
id = 51
dt = 0
[[operations]]
pre = [[7, 90]]
post = [[8, 264]]
station_id = 8
id = 52
dt = 0
[[operations]]
pre = [[5, 510], [6, 74]]
post = [[7, 209]]
station_id = 7
id = 53
dt = 0
[[operations]]
pre = [[4, 137]]
post = [[6, 538]]
station_id = 6
id = 54
dt = 0
[[operations]]
pre = [[2, 265], [3, 482]]
post = [[5, 225]]
station_id = 5
id = 55
dt = 0
[[operations]]
pre = [[1, 68]]
post = [[2, 398]]
station_id = 2
id = 56
dt = 0
[[operations]]
pre = [[10, 259]]
post = []
station_id = -1
id = 57
dt = 0
