final_conditions = [[1, 4], [2, 5], [3, 6]]
t_request = 10
r0 = []
s0 = [1, 2, 3]
sF = [4, 5, 6]
t_arrival = 10
shapes = [[1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 1], [2, 2], [3, 3]]

[[operations]]
pre = [[1, 4], [2, 5]]
post = [[3, 3]]
station_id = -1
id = 121
dt = 0
[[operations]]
pre = [[3, 6]]
post = []
station_id = -1
id = 122
dt = 0
